version: "3.8"
services:
  app:
    # image: php:8.3.3RC1-apache
    build: ./php/.
    container_name: php
    restart: always
    ports:
      - "80:80"
    volumes:
      - "../website/:/var/www/"

